export const ACTION_HOME_BANNERS_REQUEST = "action_home_banners_request";
export const ACTION_HOME_BANNERS_SUCCESS = "action_home_banners_success";
export const ACTION_HOME_BANNERS_FAILURE = "action_home_banners_failure";

export const ACTION_HOME_HOT_UPDATES_REQUEST = "action_home_hot_updates_request";
export const ACTION_HOME_HOT_UPDATES_SUCCESS = "action_home_hot_updates_success";
export const ACTION_HOME_HOT_UPDATES_FAILURE = "action_home_hot_updates_failure";

export const ACTION_HOME_LATEST_UPDATES_REQUEST = "action_home_latest_updates_request";
export const ACTION_HOME_LATEST_UPDATES_SUCCESS = "action_home_latest_updates_success";
export const ACTION_HOME_LATEST_UPDATES_FAILURE = "action_home_latest_updates_failure";

// export const ACTION_NANO_GENRES_REQUEST = "action_nano_genres_request";
// export const ACTION_NANO_GENRES_SUCCESS = "action_nano_genres_success";
// export const ACTION_NANO_GENRES_FAILURE = "action_nano_genres_failure";

export const ACTION_GET_ALL_SERIE_REQUEST = "action_get_all_serie_request";
export const ACTION_GET_ALL_SERIE_SUCCESS = "action_get_all_serie_success";
export const ACTION_GET_ALL_SERIE_FAILURE = "action_get_all_serie_failure";

export const ACTION_SET_ALL_MANGA_FILTER_OPTIONS = "action_set_all_manga_filter_options";
export const ACTION_RESET_ALL_MANGA_FILTER_OPTIONS = "action_reset_all_manga_filter_options";
export const ACTION_LOAD_MORE_ALL_MANGA = "action_load_more_all_manga";
export const ACTION_LOAD_ALL_MANGA_ITEMS = "action_load_all_manga_items";


// Latest updates page's actions
export const ACTION_LATEST_UPDATES_REQUEST = "action_latest_updates_request";
export const ACTION_LATEST_UPDATES_SUCCESS = "action_latest_updates_success";
export const ACTION_LATEST_UPDATES_FAILURE = "action_latest_updates_failure";

export const ACTION_SET_LATEST_UPDATES_FILTER_OPTIONS = "action_set_latest_updates_filter_options";
export const ACTION_RESET_LATEST_UPDATES_FILTER_OPTIONS = "action_reset_latest_updates_filter_options";

// Retrieve manga detail actions
export const ACTION_MANGA_DETAIL_REQUEST = "ACTION_MANGA_DETAIL_REQUEST";
export const ACTION_MANGA_DETAIL_SUCCESS = "ACTION_MANGA_DETAIL_SUCCESS";
export const ACTION_MANGA_DETAIL_FAILURE = "ACTION_MANGA_DETAIL_FAILURE";

// NANO_AUTHORS actions
// export const ACTION_NANO_AUTHORS_REQUEST = "ACTION_NANO_AUTHORS_REQUEST";
// export const ACTION_NANO_AUTHORS_SUCCESS = "ACTION_NANO_AUTHORS_SUCCESS";
// export const ACTION_NANO_AUTHORS_FAILURE = "ACTION_NANO_AUTHORS_FAILURE";

// NANO_CHARACTER actions
// export const ACTION_NANO_CHARACTER_REQUEST = "ACTION_NANO_CHARACTER_REQUEST";
// export const ACTION_NANO_CHARACTER_SUCCESS = "ACTION_NANO_CHARACTER_SUCCESS";
// export const ACTION_NANO_CHARACTER_FAILURE = "ACTION_NANO_CHARACTER_FAILURE";

// NANO_SERIE actions
// export const ACTION_NANO_SERIE_REQUEST = "ACTION_NANO_SERIE_REQUEST";
// export const ACTION_NANO_SERIE_SUCCESS = "ACTION_NANO_SERIE_SUCCESS";
// export const ACTION_NANO_SERIE_FAILURE = "ACTION_NANO_SERIE_FAILURE";

// MANGA_CHAPTERS actions
export const ACTION_MANGA_CHAPTERS_REQUEST = "ACTION_MANGA_CHAPTERS_REQUEST";
export const ACTION_MANGA_CHAPTERS_SUCCESS = "ACTION_MANGA_CHAPTERS_SUCCESS";
export const ACTION_MANGA_CHAPTERS_FAILURE = "ACTION_MANGA_CHAPTERS_FAILURE";

// MANGA_CHAPTER_PAGE actions
export const ACTION_MANGA_CHAPTER_PAGE_REQUEST = "ACTION_MANGA_CHAPTER_PAGE_REQUEST";
export const ACTION_MANGA_CHAPTER_PAGE_SUCCESS = "ACTION_MANGA_CHAPTER_PAGE_SUCCESS";
export const ACTION_MANGA_CHAPTER_PAGE_FAILURE = "ACTION_MANGA_CHAPTER_PAGE_FAILURE";
export const ACTION_MANGA_SET_CURRENT_CHAPTER = "ACTION_MANGA_SET_CURRENT_CHAPTER";


// GET_ALL_CHARACTER actions
export const ACTION_GET_ALL_CHARACTER_REQUEST = "ACTION_GET_ALL_CHARACTER_REQUEST";
export const ACTION_GET_ALL_CHARACTER_SUCCESS = "ACTION_GET_ALL_CHARACTER_SUCCESS";
export const ACTION_GET_ALL_CHARACTER_FAILURE = "ACTION_GET_ALL_CHARACTER_FAILURE";


export const ACTION_SET_ALL_CHARACTER_FILTER_OPTIONS = "action_set_all_character_filter_options";
export const ACTION_ALL_CHARACTER_LOAD_MORE = "action_all_character_load_more";

// GET_CHARACTER_DETAIL actions
export const ACTION_GET_CHARACTER_DETAIL_REQUEST = "ACTION_GET_CHARACTER_DETAIL_REQUEST";
export const ACTION_GET_CHARACTER_DETAIL_SUCCESS = "ACTION_GET_CHARACTER_DETAIL_SUCCESS";
export const ACTION_GET_CHARACTER_DETAIL_FAILURE = "ACTION_GET_CHARACTER_DETAIL_FAILURE";

// GET_CHARACTER_RELATED_SERIES actions
export const ACTION_GET_CHARACTER_RELATED_SERIES_REQUEST = "ACTION_GET_CHARACTER_RELATED_SERIES_REQUEST";
export const ACTION_GET_CHARACTER_RELATED_SERIES_SUCCESS = "ACTION_GET_CHARACTER_RELATED_SERIES_SUCCESS";
export const ACTION_GET_CHARACTER_RELATED_SERIES_FAILURE = "ACTION_GET_CHARACTER_RELATED_SERIES_FAILURE";


// GET_ALL_AUTHOR actions
export const ACTION_GET_ALL_AUTHOR_REQUEST = "ACTION_GET_ALL_AUTHOR_REQUEST";
export const ACTION_GET_ALL_AUTHOR_SUCCESS = "ACTION_GET_ALL_AUTHOR_SUCCESS";
export const ACTION_GET_ALL_AUTHOR_FAILURE = "ACTION_GET_ALL_AUTHOR_FAILURE";

export const ACTION_SET_ALL_AUTHOR_FILTER_OPTIONS = "action_set_all_author_filter_options";
export const ACTION_ALL_AUTHOR_LOAD_MORE = "action_all_author_load_more";

// GET_AUTHOR_DETAIL actions
export const ACTION_GET_AUTHOR_DETAIL_REQUEST = "ACTION_GET_AUTHOR_DETAIL_REQUEST";
export const ACTION_GET_AUTHOR_DETAIL_SUCCESS = "ACTION_GET_AUTHOR_DETAIL_SUCCESS";
export const ACTION_GET_AUTHOR_DETAIL_FAILURE = "ACTION_GET_AUTHOR_DETAIL_FAILURE";

// GET_AUTHOR_RELATED_SERIES actions
export const ACTION_GET_AUTHOR_RELATED_SERIES_REQUEST = "ACTION_GET_AUTHOR_RELATED_SERIES_REQUEST";
export const ACTION_GET_AUTHOR_RELATED_SERIES_SUCCESS = "ACTION_GET_AUTHOR_RELATED_SERIES_SUCCESS";
export const ACTION_GET_AUTHOR_RELATED_SERIES_FAILURE = "ACTION_GET_AUTHOR_RELATED_SERIES_FAILURE";

// GET_GENRE_DETAIL actions
export const ACTION_GET_GENRE_DETAIL_REQUEST = "ACTION_GET_GENRE_DETAIL_REQUEST";
export const ACTION_GET_GENRE_DETAIL_SUCCESS = "ACTION_GET_GENRE_DETAIL_SUCCESS";
export const ACTION_GET_GENRE_DETAIL_FAILURE = "ACTION_GET_GENRE_DETAIL_FAILURE";

// GET_TOP_POPULAR actions
export const ACTION_GET_TOP_POPULAR_REQUEST = "ACTION_GET_TOP_POPULAR_REQUEST";
export const ACTION_GET_TOP_POPULAR_SUCCESS = "ACTION_GET_TOP_POPULAR_SUCCESS";
export const ACTION_GET_TOP_POPULAR_FAILURE = "ACTION_GET_TOP_POPULAR_FAILURE";

// GET_READ_RIGHT_NOW actions
export const ACTION_GET_READ_RIGHT_NOW_REQUEST = "ACTION_GET_READ_RIGHT_NOW_REQUEST";
export const ACTION_GET_READ_RIGHT_NOW_SUCCESS = "ACTION_GET_READ_RIGHT_NOW_SUCCESS";
export const ACTION_GET_READ_RIGHT_NOW_FAILURE = "ACTION_GET_READ_RIGHT_NOW_FAILURE";

// DO_QUICK_SEARCH actions
export const ACTION_DO_QUICK_SEARCH_REQUEST = "ACTION_DO_QUICK_SEARCH_REQUEST";
export const ACTION_DO_QUICK_SEARCH_SUCCESS = "ACTION_DO_QUICK_SEARCH_SUCCESS";
export const ACTION_DO_QUICK_SEARCH_FAILURE = "ACTION_DO_QUICK_SEARCH_FAILURE";

// SEARCH_SERIE actions
export const ACTION_SEARCH_SERIE_REQUEST = "ACTION_SEARCH_SERIE_REQUEST";
export const ACTION_SEARCH_SERIE_SUCCESS = "ACTION_SEARCH_SERIE_SUCCESS";
export const ACTION_SEARCH_SERIE_FAILURE = "ACTION_SEARCH_SERIE_FAILURE";

// SEARCH_AUTHOR actions
export const ACTION_SEARCH_AUTHOR_REQUEST = "ACTION_SEARCH_AUTHOR_REQUEST";
export const ACTION_SEARCH_AUTHOR_SUCCESS = "ACTION_SEARCH_AUTHOR_SUCCESS";
export const ACTION_SEARCH_AUTHOR_FAILURE = "ACTION_SEARCH_AUTHOR_FAILURE";

// SEARCH_CHARACTER actions
export const ACTION_SEARCH_CHARACTER_REQUEST = "ACTION_SEARCH_CHARACTER_REQUEST";
export const ACTION_SEARCH_CHARACTER_SUCCESS = "ACTION_SEARCH_CHARACTER_SUCCESS";
export const ACTION_SEARCH_CHARACTER_FAILURE = "ACTION_SEARCH_CHARACTER_FAILURE";

export const ACTION_QUICK_SEARCH_SET_SEARCH_TEXT = "ACTION_QUICK_SEARCH_SET_SEARCH_TEXT";
export const ACTION_QUICK_SEARCH_FOCUS = "ACTION_QUICK_SEARCH_FOCUS";
export const ACTION_QUICK_SEARCH_LOST_FOCUS = "ACTION_QUICK_SEARCH_LOST_FOCUS";

export const ACTION_SEARCH_RESET = "ACTION_SEARCH_RESET";
export const ACTION_SEARCH_SET_SEARCH_TEX = "ACTION_SEARCH_SET_SEARCH_TEX";

export const ACTION_UPDATE_META = "ACTION_UPDATE_META";
export const ACTION_UPDATE_META_REQUEST = "ACTION_UPDATE_META_REQUEST";
export const ACTION_SET_ALL_GENRES = "ACTION_SET_ALL_GENRES";

// user login action
export const ACTION_USER_LOGIN_REQUEST = "action_user_login_request";
export const ACTION_USER_LOGIN_SUCCESS = "action_user_login_success";
export const ACTION_USER_LOGIN_FAILURE = "action_user_login_failure";
// user facebook login action
export const ACTION_FACEBOOK_LOGIN_REQUEST = "action_facebook_login_request";
export const ACTION_FACEBOOK_LOGIN_SUCCESS = "action_facebook_login_success";
export const ACTION_FACEBOOK_LOGIN_FAILURE = "action_facebook_login_failure";

// user login action
export const ACTION_USER_SIGNUP_REQUEST = "action_user_signup_request";
export const ACTION_USER_SIGNUP_SUCCESS = "action_user_signup_success";
export const ACTION_USER_SIGNUP_FAILURE = "action_user_signup_failure";

// GET ISSUE TYPE LIST
export const ACTION_GET_ISSUE_TYPES_REQUEST = "action_get_issue_types_request";
export const ACTION_GET_ISSUE_TYPES_SUCCESS = "action_get_issue_types_success";
export const ACTION_GET_ISSUE_TYPES_FAILURE = "action_get_issue_types_failure";

// CREATE ISSUE
export const ACTION_CREATE_ISSUE_REQUEST = "action_create_issue_request";
export const ACTION_CREATE_ISSUE_SUCCESS = "action_create_issue_success";
export const ACTION_CREATE_ISSUE_FAILURE = "action_create_issue_failure";

// GET ISSUE LIST
export const ACTION_GET_ISSUE_LIST_REQUEST = "action_get_issue_list_request";
export const ACTION_GET_ISSUE_LIST_SUCCESS = "action_get_issue_list_success";
export const ACTION_GET_ISSUE_LIST_FAILURE = "action_get_issue_List_failure";

// GET ISSUE LIST
export const ACTION_GET_ISSUES_REQUEST = "action_get_issues_request";
export const ACTION_GET_ISSUES_SUCCESS = "action_get_issues_success";
export const ACTION_GET_ISSUES_FAILURE = "action_get_issues_failure";

// GET ISSUE DETAIL
export const ACTION_GET_ISSUE_REQUEST = "action_get_issue_request";
export const ACTION_GET_ISSUE_SUCCESS = "action_get_issue_success";
export const ACTION_GET_ISSUE_FAILURE = "action_get_issue_failure";

// UNRESOLVE ISSUE
export const ACTION_UNRESOLVE_ISSUE_REQUEST = "action_unresolve_issue_request";
export const ACTION_UNRESOLVE_ISSUE_SUCCESS = "action_unresolve_issue_success";
export const ACTION_UNRESOLVE_ISSUE_FAILURE = "action_unresolve_issue_failure";

// TOGGLE ISSUE MODAL
export const ACTION_TOGGLE_ISSUE_MODAL = "action_toggle_issue_modal";

export const ACTION_SET_HUD_CONTENT = "ACTION_SET_HUD_CONTENT";
export const ACTION_SET_SNACKBAR_CONTENT = "ACTION_SET_SNACKBAR_CONTENT";

export const ACTION_OPEN_GET_APP_BAR = "ACTION_OPEN_GET_APP_BAR";
export const ACTION_CLOSE_GET_APP_BAR = "ACTION_CLOSE_GET_APP_BAR";
export const ACTION_GET_DEEPLINK_REQUEST = "ACTION_GET_DEEPLINK_REQUEST";

// GET_MANGA_SUGGESTION actions
export const ACTION_GET_MANGA_SUGGESTION_REQUEST = "ACTION_GET_MANGA_SUGGESTION_REQUEST";
export const ACTION_GET_MANGA_SUGGESTION_SUCCESS = "ACTION_GET_MANGA_SUGGESTION_SUCCESS";
export const ACTION_GET_MANGA_SUGGESTION_FAILURE = "ACTION_GET_MANGA_SUGGESTION_FAILURE";

// GET_COLLECTION_INFO actions
export const ACTION_GET_COLLECTION_INFO_REQUEST = "ACTION_GET_COLLECTION_INFO_REQUEST";
export const ACTION_GET_COLLECTION_INFO_SUCCESS = "ACTION_GET_COLLECTION_INFO_SUCCESS";
export const ACTION_GET_COLLECTION_INFO_FAILURE = "ACTION_GET_COLLECTION_INFO_FAILURE";

// GET_COLLECTION_MANGA_LIST_INFO actions
export const ACTION_GET_COLLECTION_MANGA_LIST_INFO_REQUEST = "ACTION_GET_COLLECTION_MANGA_LIST_INFO_REQUEST";
export const ACTION_GET_COLLECTION_MANGA_LIST_INFO_SUCCESS = "ACTION_GET_COLLECTION_MANGA_LIST_INFO_SUCCESS";
export const ACTION_GET_COLLECTION_MANGA_LIST_INFO_FAILURE = "ACTION_GET_COLLECTION_MANGA_LIST_INFO_FAILURE";
